spring:
  application:
    name: cake-platform

  datasource:
    # 환경변수 설정 파일
    url: jdbc:mysql://localhost:3306/cake?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vkflwldod3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true