spring:
  application:
    name: cake-platform

  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect  # 이 줄 추가
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}

server:
  port: 8080

  KAKAO_CLIENT_ID: dummy
  KAKAO_CLIENT_SECRET: dummy
